name: capstone-tf2
channels:
  - conda-forge

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow==2.1.0
    - tensorflow-gpu==2.1.0
    - opencv-python==4.1.1.26
    - bcolz==1.2.1
    - sklearn2
    - PyYAML
    - tqdm
